[package]
name = "machine-learning"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dragon_math = { path = "../math" }
dragon_model = { path = "../model" }